### ISSUE TITLE
Not working with Torch 2.5.1

### ISSUE THREAD

**Issue by sibocw** [NeLy-EPFL/flygym#224]
Upon building autodoc, I encountered the following import error:
```
$ cd doc
$ make html                             
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
[autosummary] generating autosummary for: api_ref/arena.rst, api_ref/camera.rst, api_ref/examples/head_stabilization.rst, api_ref/examples/index.rst, api_ref/examples/locomotion.rst, api_ref/examples/olfaction.rst, api_ref/examples/path_integration.rst, api_ref/examples/vision.rst, api_ref/fly.rst, api_ref/index.rst, ..., tutorials/cpg_controller.rst, tutorials/gym_basics_and_kinematic_replay.rst, tutorials/head_stabilization.rst, tutorials/hybrid_controller.rst, tutorials/index.rst, tutorials/olfaction_basics.rst, tutorials/path_integration.rst, tutorials/rule_based_controller.rst, tutorials/turning.rst, tutorials/vision_basics.rst
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 46 source files that are out of date
updating environment: [new config] 46 added, 0 changed, 0 removed
/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torch/__init__.py:1144: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
reading sources... [100%] tutorials/vision_basics
WARNING: autodoc: failed to import class 'vision.arena.ObstacleOdorArena' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
WARNING: autodoc: failed to import class 'vision.simple_visual_taxis.VisualTaxis' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
WARNING: autodoc: failed to import class 'vision.RealTimeVisionNetwork' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
WARNING: autodoc: failed to import class 'vision.RealTimeVisionNetworkView' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
WARNING: autodoc: failed to import class 'vision.RetinaMapper' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
WARNING: autodoc: failed to import class 'vision.RealisticVisionFly' from module 'flygym.examples'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/sphinx/ext/autodoc/importer.py", line 143, in import_module
    return importlib.import_module(modname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/__init__.py", line 2, in <module>
    from .vision_network import (
  File "/home/sibwang/Projects/flygym/flygym/examples/vision/vision_network.py", line 3, in <module>
    import flyvision
  File "/home/sibwang/Projects/flyvis/flyvision/__init__.py", line 22, in <module>
    from flyvision._api import *
  File "/home/sibwang/Projects/flyvis/flyvision/_api.py", line 5, in <module>
    from flyvision import rendering
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/__init__.py", line 3, in <module>
    from flyvision.rendering.eye import BoxEye
  File "/home/sibwang/Projects/flyvis/flyvision/rendering/eye.py", line 11, in <module>
    import torchvision.transforms.functional as ttf
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 25, in <module>
    @register_meta("roi_align")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sibwang/anaconda3/envs/flygym/lib/python3.11/site-packages/torchvision/_meta_registrations.py", line 18, in wrapper
    if torchvision.extension._has_ops():
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)
 [autodoc.import_object]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... 
copying static files... 
Writing evaluated template result to /home/sibwang/Projects/flygym/doc/build/html/_static/documentation_options.js
Writing evaluated template result to /home/sibwang/Projects/flygym/doc/build/html/_static/basic.css
Writing evaluated template result to /home/sibwang/Projects/flygym/doc/build/html/_static/language_data.js
copying static files: done
copying extra files... 
copying extra files: done
copying assets: done
writing output... [100%] tutorials/vision_basics
generating indices... genindex py-modindex done
writing additional pages... search done
copying images... [100%] _static/fly_anatomy.jpg
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 6 warnings.

The HTML pages are in build/html.
```

**Comment by stepanove** [comment]
There is an issue with reverting to torch 2.5.0.

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> torchvision 0.20.1 requires torch==2.5.1, but you have torch 2.5.0 which is incompatible.

I usppose tochvision is used in flyvis.

**Comment by sibocw** [comment]
Thanks Dom! See #229
